#!/usr/bin/env bash
# vim: set ft=bash:

set -e
set -o pipefail

all_window_ids=$(cat "/var/run/user/$(id -u)/i3containerbackandforthd/history" || true)
this_window_id=$(head -n 1 <<< "$all_window_ids")
window_ids=$(tail -n +1 <<< "$all_window_ids")

if ! [ "$all_window_ids" ]; then
	# Nothing we can do...
	exit
fi

if [ "$1" != "-n" ] && [ "$1" != "--dry-run" ]; then
	for window_id in $window_ids; do
		if [ "$window_id" = "$this_window_id" ]; then
			continue
		fi
		if i3-msg -q "[con_id=$window_id] focus"; then
			exit 0
		fi
	done
fi

exit 1
