#!/usr/bin/env bash
# vim: set ft=bash:

# swaps the visible workspaces between the two attached outputs
# does nothing if more or less than two outputs are attached

outputs_json=$(i3-msg -t get_outputs | jq 'map(select(.active))')

if [ "$(jq -r 'length' <<< "$outputs_json")" -ne 2 ]; then
	exit
fi

workspaces_json=$(i3-msg -t get_workspaces)
active_output_json=$(jq '.[] | select(.focused) | .output' <<< "$workspaces_json")
active_output=$(jq -r <<< "$active_output_json")
inactive_output=$(jq -r ".[] | select(.name != $active_output_json) | .name" <<< "$outputs_json")
inactive_workspace=$(jq -r ".[] | select(.output != $active_output_json) | select(.visible) | .name" <<< "$workspaces_json")

i3-msg -q "focus output $active_output, move workspace to output $inactive_output; workspace $inactive_workspace, move workspace to output $active_output"
