#!/usr/bin/env nix-script-bash
#!runtimeInputs imagemagick dunst
# vim: set ft=bash:
# shellcheck shell=bash

# locks the screen, then forks

invis=00000000

white=ffffff
black=000000
redd=cc241d
redl=fb4934
greend=98971a
greenl=b8bb26
blued=458558
bluel=83a598
purpled=b16286
purplel=d3869b

blue=5bcefa
pink=f5a9b8

ff=ff
mid=88
ish=33
trans=00

wallpaper=~/.background-image
lockscreen=~/.background-image-lockscreen
overlay=~/.background-image-lockscreen-overlay

# Check that the lockscreen image is up-to-date
if [ ! -e "$lockscreen" ] || [ "$(stat -c %Y "$lockscreen")" -lt "$(stat -c %Y "$wallpaper")" ] || [ "$(stat -c %Y "$lockscreen")" -lt "$(stat -c %Y "$overlay")" ] || [ "$(stat -c %Y "$lockscreen")" -lt "$(stat -Lc %Y "$0")" ]; then
	printf 'Updating lockscreen... '
	# https://www.imagemagick.org/Usage/resize/#fill
	# Scale the image to fill 1920x1080 (and maybe overflow it), then resize the canvas around the centre of the image and blur.
	convert "$wallpaper" -colorspace LUV -resize 1920x1080^ -gravity center -extent 1920x1080 -blur 0x10 -colorspace sRGB "$overlay" -composite "$lockscreen"
	printf 'done.\n'
else
	printf 'Lockscreen up-to-date.\n'
fi

pkill -USR1 dunst || true

i3lock-color \
	--nofork \
	--fill \
	--clock \
	--force-clock \
	--time-pos="ix:iy-168" \
	--time-size=48 \
	--time-font="Jost*" \
	--time-color="$black$ff" \
	--time-str="%-I:%M %P" \
	--date-pos="tx:ty-64" \
	--date-size=24 \
	--date-font="Jost*" \
	--date-color="$black$ff" \
	--date-str="%A %F" \
	--color="111e2f$ff" \
	--image="$lockscreen" \
	--radius=400 \
	--ring-width=10.0 \
	--inside-color="$invis" \
	--insidever-color="$invis" \
	--insidewrong-color="$invis" \
	--line-color="$invis" \
	--ring-color="$blue$trans" \
	--ringver-color="$white$trans" \
	--ringwrong-color="$redl$trans" \
	--keyhl-color="$pink$trans" \
	--bshl-color="$pink$trans" \
	--separator-color="$invis" \
	--layout-color="$black$ff" \
	--wrong-color="$invis" \
	--verif-text="" \
	--wrong-text="" \
	--noinput-text="" \
	--lock-text="locking…" \
	--lockfailed-text="locking failed!" \
	--password-box \
	--pass-media-keys \
	--pass-screen-keys \
	--pass-textier-keys \
	&

if [ $# -gt 0 ]; then
	sleep 1
	if jobs %% >/dev/null; then # if i3lock is still running
		"$@" || true
	fi
fi

wait %% || true

pkill -USR2 dunst || true
