{
  imports = [
    ./any-nix-shell.nix
    ./bash.nix
    ./bat.nix
    ./brightnessctl.nix
    ./colordiff.nix
    ./dconf-editor.nix
    ./dircolors.nix
    ./discord.nix
    ./display-volume.nix
    ./dunst.nix
    ./evince.nix
    ./exa.nix
    ./fd.nix
    ./ffmpeg.nix
    ./fish
    ./flameshot.nix
    ./frescobaldi.nix
    ./fzf.nix
    ./gammastep.nix
    ./git.nix
    ./hexchat
    ./htop.nix
    ./httpie.nix
    ./i3
    ./insync.nix
    ./jq.nix
    ./kdeconnect.nix
    ./kdenlive.nix
    ./keepassxc.nix
    ./keychain.nix
    ./kitty
    ./less.nix
    ./lutris.nix
    ./lyx.nix
    ./nemo.nix
    ./neovim
    ./nix-script.nix
    ./notify-send.nix
    ./playerctl.nix
    ./rcu
    ./ripgrep.nix
    ./rustup.nix
    ./signal.nix
    ./slack.nix
    ./some.nix
    ./starship.nix
    ./steam.nix
    ./talon
    ./todoist.nix
    ./unicode.nix
    ./vim
    ./wine.nix
    ./x
    ./xclip.nix
    ./youtube-dl.nix
    ./zenity.nix
  ];
}
