{
  imports = [
    ./any-nix-shell.nix
    ./bash.nix
    ./bat.nix
    ./brightnessctl.nix
    ./colordiff.nix
    ./dircolors.nix
    ./discord.nix
    ./exa.nix
    ./fd.nix
    ./fish
    ./flameshot.nix
    ./fzf.nix
    ./gammastep.nix
    ./git.nix
    ./htop.nix
    ./i3
    ./insync.nix
    ./kdeconnect.nix
    ./keepassxc.nix
    ./keychain.nix
    ./kitty
    ./less.nix
    ./nemo.nix
    ./nix-script.nix
    ./ripgrep.nix
    ./slack.nix
    ./starship.nix
    ./todoist.nix
    ./vim.nix
    ./x
    ./xclip.nix
  ];
}
