{
  imports = [
    ./7zip.nix
    ./any-nix-shell.nix
    ./bash.nix
    ./bat.nix
    ./bintools.nix
    ./brightnessctl.nix
    ./calculator.nix
    ./calibre.nix
    ./colordiff.nix
    ./dconf-editor.nix
    ./dig.nix
    ./dircolors.nix
    ./direnv.nix
    ./discord.nix
    ./display-volume.nix
    ./dunst.nix
    ./evince.nix
    ./exa.nix
    ./exiftool.nix
    ./fd.nix
    ./ffmpeg.nix
    ./file2img
    ./firefox.nix
    ./fish
    ./flac.nix
    ./flameshot.nix
    ./frescobaldi.nix
    ./fzf.nix
    ./gammastep.nix
    ./gdb.nix
    ./git.nix
    ./gpg.nix
    ./hexchat
    ./htop.nix
    ./httpie.nix
    ./hushboard.nix
    ./i3
    ./inkscape.nix
    ./insync.nix
    ./jq.nix
    ./kdeconnect.nix
    ./kdenlive.nix
    ./keepassxc.nix
    ./keychain.nix
    ./kid3.nix
    ./kitty
    ./less.nix
    ./libreoffice.nix
    ./lorri.nix
    ./lsof.nix
    ./lyx.nix
    ./make.nix
    ./nemo.nix
    ./neovim
    ./nix-script.nix
    ./nix.nix
    ./notify-send.nix
    ./obs.nix
    ./obsidian.nix
    ./peek.nix
    ./playerctl.nix
    ./pngcrush.nix
    ./qutebrowser
    ./rcu
    ./readline.nix
    ./rhythmbox.nix
    ./ripgrep.nix
    ./rustup.nix
    ./signal.nix
    ./slack.nix
    ./some.nix
    ./sqlitebrowser.nix
    ./ssh.nix
    ./starship.nix
    ./steam.nix
    ./systemd.nix
    ./talon
    ./todoist.nix
    ./unicode.nix
    ./vim
    ./whois.nix
    ./wine.nix
    ./wxhexeditor.nix
    ./x
    ./xclip.nix
    ./youtube-dl.nix
    ./zenity.nix
    ./zip.nix
    ./zoom.nix
    ./zotero.nix
    ./zulip.nix
  ];
}
